services:
  minhaaplicacao:
    build:
      context: .
    container_name: order-processing-system
    ports:
        - "9090:8080" 
    restart: always
    volumes:
      - ./local/diretorio:/app/diretorio-no-container
